2023-10-12 11:31:20,493 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 11:33:38,675 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 11:34:51,189 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-12 11:34:51,190 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-12 11:34:51,191 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 11:35:09,548 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-12 11:35:09,549 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-12 11:35:09,553 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 11:35:11,294 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 11:35:11,294 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 11:35:17,538 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 11:35:16.622028
2023-10-12 11:35:42,180 INFO app Thread-7 (process_request_thread) : {'message': "'dict' object has no attribute 'decode'", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 112, in fetch_and_store_data', '    send_mail(message)', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 203, in send_mail', '    mail.send(msg)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 492, in send', '    message.send(connection)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 427, in send', '    connection.send(self)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 190, in send', '    message.as_bytes() if PY3 else message.as_string(),', '    ^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 385, in as_bytes', '    return self._message().as_bytes()', '           ^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 324, in _message', "    alternative.attach(self._mimetext(self.html, 'html'))", '                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 303, in _mimetext', '    return MIMEText(text, _subtype=subtype, _charset=charset)', '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/usr/lib/python3.11/email/mime/text.py", line 41, in __init__', '    self.set_payload(_text, _charset)', '  File "/usr/lib/python3.11/email/message.py", line 348, in set_payload', '    self.set_charset(charset)', '  File "/usr/lib/python3.11/email/message.py", line 383, in set_charset', '    cte(self)', '  File "/usr/lib/python3.11/email/encoders.py", line 57, in encode_7or8bit', "    orig.decode('ascii')", '    ^^^^^^^^^^^', "AttributeError: 'dict' object has no attribute 'decode'"]}
2023-10-12 11:35:42,187 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 11:35:42] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2023-10-12 11:36:30,228 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 11:36:32,476 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 11:36:34,178 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 11:36:34,179 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 11:36:40,230 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 11:36:40.229929
2023-10-12 11:36:40,997 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 11:36:40] "POST / HTTP/1.1" 200 -
2023-10-12 12:06:58,822 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 12:07:01,047 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 12:07:02,649 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 12:07:02,649 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 12:07:06,881 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 12:07:06.881277
2023-10-12 12:07:06,895 INFO app Thread-7 (process_request_thread) : {'message': "name 'username' is not defined", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 105, in fetch_and_store_data', '    username=username,', '             ^^^^^^^^', "NameError: name 'username' is not defined"]}
2023-10-12 12:07:06,898 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:07:06] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2023-10-12 12:07:24,729 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 12:07:29,975 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 12:07:31,621 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 12:07:31,622 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 12:07:32,514 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 12:07:32.514157
2023-10-12 12:07:34,696 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:07:34] "POST / HTTP/1.1" 200 -
2023-10-12 12:11:35,861 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 12:16:19,819 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 12:16:21,447 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 12:16:21,448 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 12:16:21,873 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 12:16:21.873250
2023-10-12 12:18:40,848 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 12:18:43,264 INFO app Thread-7 (process_request_thread) : {'message': "name 'username' is not defined", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 107, in fetch_and_store_data', "    username=data['user']['username'],", '             ^^^^^^^^', "NameError: name 'username' is not defined"]}
2023-10-12 12:18:43,370 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:18:43] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2023-10-12 12:18:44,249 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 12:18:45,970 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 12:18:45,971 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 12:18:47,478 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 12:18:47.478374
2023-10-12 12:18:49,617 INFO app Thread-7 (process_request_thread) : {'message': "Could not build url for endpoint 'track_and_trace' with values ['token', 'username']. Did you mean 'fetch_and_store_data' instead?", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 105, in fetch_and_store_data', '    login_url = url_for(', '                ^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 225, in url_for', '    return current_app.url_for(', '           ^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1697, in url_for', '    return self.handle_url_build_error(error, endpoint, values)', '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1686, in url_for', '    rv = url_adapter.build(  # type: ignore[union-attr]', '         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 950, in build', '    raise BuildError(endpoint, values, method, self)', "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'track_and_trace' with values ['token', 'username']. Did you mean 'fetch_and_store_data' instead?"]}
2023-10-12 12:18:49,620 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:18:49] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2023-10-12 12:21:42,058 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 12:21:44,700 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 12:21:46,445 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 12:21:46,445 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 12:21:49,735 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 12:21:49.735055
2023-10-12 12:21:51,675 INFO app Thread-7 (process_request_thread) : {'message': "Could not build url for endpoint 'track_and_trace' with values ['token', 'username']. Did you mean 'fetch_and_store_data' instead?", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 105, in fetch_and_store_data', '    login_url = url_for(', '                ^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 225, in url_for', '    return current_app.url_for(', '           ^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1697, in url_for', '    return self.handle_url_build_error(error, endpoint, values)', '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1686, in url_for', '    rv = url_adapter.build(  # type: ignore[union-attr]', '         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 950, in build', '    raise BuildError(endpoint, values, method, self)', "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'track_and_trace' with values ['token', 'username']. Did you mean 'fetch_and_store_data' instead?"]}
2023-10-12 12:21:51,680 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:21:51] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2023-10-12 12:22:14,690 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 12:22:18,114 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 12:22:42,832 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-12 12:22:42,833 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-12 12:22:42,834 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 12:23:04,569 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-12 12:23:04,569 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-12 12:23:04,571 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 12:23:06,229 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 12:23:06,230 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 12:23:12,115 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 12:23:12.115174
2023-10-12 12:23:14,356 INFO app Thread-7 (process_request_thread) : {'message': "name 'msg' is not defined", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 110, in fetch_and_store_data', '    msg.html = f"Click the following link to log in: <a href=\'{login_url}\' target=\'_blank\' rel=\'noopener noreferrer\'>Log In</a>"', '    ^^^', "NameError: name 'msg' is not defined"]}
2023-10-12 12:23:14,360 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:23:14] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2023-10-12 12:24:39,175 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 12:24:41,547 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 12:24:43,213 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 12:24:43,213 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 12:24:43,424 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 12:24:43.423912
2023-10-12 12:24:45,342 INFO app Thread-7 (process_request_thread) : {'message': "send_mail() missing 1 required positional argument: 'message'", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 104, in fetch_and_store_data', '    send_mail()', "TypeError: send_mail() missing 1 required positional argument: 'message'"]}
2023-10-12 12:24:45,345 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:24:45] "[35m[1mPOST / HTTP/1.1[0m" 500 -
2023-10-12 12:25:05,286 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 12:25:07,017 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 12:25:08,646 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 12:25:08,647 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 12:25:09,860 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 12:25:09.860127
2023-10-12 12:25:10,676 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:25:10] "POST / HTTP/1.1" 200 -
2023-10-12 12:25:18,410 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:25:18] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 12:25:18,416 INFO app Thread-9 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 12:25:18,416 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:25:18] "[35m[1mGET /www.google.com HTTP/1.1[0m" 500 -
2023-10-12 12:26:44,522 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 12:26:47,882 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 12:26:49,484 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 12:26:49,485 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 12:26:51,467 INFO app Thread-7 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 12:26:51,469 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:26:51] "[35m[1mGET /www.google.com HTTP/1.1[0m" 500 -
2023-10-12 12:26:52,953 INFO app Thread-8 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 12:26:52,955 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:26:52] "[35m[1mGET /www.google.com HTTP/1.1[0m" 500 -
2023-10-12 12:26:53,374 INFO app Thread-9 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 12:26:53,375 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:26:53] "[35m[1mGET /www.google.com HTTP/1.1[0m" 500 -
2023-10-12 12:26:53,588 INFO app Thread-10 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 12:26:53,588 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:26:53] "[35m[1mGET /www.google.com HTTP/1.1[0m" 500 -
2023-10-12 12:26:53,782 INFO app Thread-11 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 12:26:53,783 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:26:53] "[35m[1mGET /www.google.com HTTP/1.1[0m" 500 -
2023-10-12 12:26:53,975 INFO app Thread-12 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 12:26:53,976 INFO werkzeug Thread-12 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:26:53] "[35m[1mGET /www.google.com HTTP/1.1[0m" 500 -
2023-10-12 12:26:54,509 INFO app Thread-13 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 12:26:54,511 INFO werkzeug Thread-13 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:26:54] "[35m[1mGET /www.google.com HTTP/1.1[0m" 500 -
2023-10-12 12:26:55,132 INFO app Thread-14 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 12:26:55,135 INFO werkzeug Thread-14 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:26:55] "[35m[1mGET /www.google.com HTTP/1.1[0m" 500 -
2023-10-12 12:27:04,330 INFO app Thread-15 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 12:27:04.330312
2023-10-12 12:27:05,021 INFO werkzeug Thread-15 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:27:05] "GET / HTTP/1.1" 200 -
2023-10-12 12:27:06,077 INFO app Thread-16 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 12:27:06.077666
2023-10-12 12:27:06,763 INFO werkzeug Thread-16 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:27:06] "GET / HTTP/1.1" 200 -
2023-10-12 12:27:11,237 INFO werkzeug Thread-17 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:27:11] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 12:29:40,017 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 12:29:43,186 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 12:29:44,837 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 12:29:44,838 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 12:29:47,441 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 12:29:47.441121
2023-10-12 12:29:49,691 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 12:29:49] "GET / HTTP/1.1" 200 -
2023-10-12 13:14:20,338 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:14:36,717 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:14:39,849 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-12 13:14:39,850 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-12 13:14:39,851 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:14:56,512 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-12 13:14:56,512 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-12 13:14:56,514 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:14:58,174 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:14:58,175 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:14:59,946 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:14:59.945914
2023-10-12 13:15:00,616 INFO app Thread-7 (process_request_thread) : {'message': "(535, b'Authentication failed')", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 106, in fetch_and_store_data', '    send_mail()', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 209, in send_mail', '    mail.send(msg)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 491, in send', '    with self.connect() as connection:', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 144, in __enter__', '    self.host = self.configure_host()', '                ^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 165, in configure_host', '    host.login(self.mail.username, self.mail.password)', '  File "/usr/lib/python3.11/smtplib.py", line 750, in login', '    raise last_exception', '  File "/usr/lib/python3.11/smtplib.py", line 739, in login', '    (code, resp) = self.auth(', '                   ^^^^^^^^^^', '  File "/usr/lib/python3.11/smtplib.py", line 662, in auth', '    raise SMTPAuthenticationError(code, resp)', "smtplib.SMTPAuthenticationError: (535, b'Authentication failed')"]}
2023-10-12 13:15:00,620 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:15:00] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 13:15:49,634 INFO app Thread-8 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:15:49.634803
2023-10-12 13:15:50,987 INFO app Thread-8 (process_request_thread) : {'message': "(535, b'Authentication failed')", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 106, in fetch_and_store_data', '    send_mail()', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 209, in send_mail', '    mail.send(msg)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 491, in send', '    with self.connect() as connection:', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 144, in __enter__', '    self.host = self.configure_host()', '                ^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 165, in configure_host', '    host.login(self.mail.username, self.mail.password)', '  File "/usr/lib/python3.11/smtplib.py", line 750, in login', '    raise last_exception', '  File "/usr/lib/python3.11/smtplib.py", line 739, in login', '    (code, resp) = self.auth(', '                   ^^^^^^^^^^', '  File "/usr/lib/python3.11/smtplib.py", line 662, in auth', '    raise SMTPAuthenticationError(code, resp)', "smtplib.SMTPAuthenticationError: (535, b'Authentication failed')"]}
2023-10-12 13:15:50,994 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:15:50] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 13:15:53,037 INFO app Thread-9 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:15:53.037244
2023-10-12 13:15:53,641 INFO app Thread-9 (process_request_thread) : {'message': "(535, b'Authentication failed')", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 106, in fetch_and_store_data', '    send_mail()', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 209, in send_mail', '    mail.send(msg)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 491, in send', '    with self.connect() as connection:', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 144, in __enter__', '    self.host = self.configure_host()', '                ^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask_mail.py", line 165, in configure_host', '    host.login(self.mail.username, self.mail.password)', '  File "/usr/lib/python3.11/smtplib.py", line 750, in login', '    raise last_exception', '  File "/usr/lib/python3.11/smtplib.py", line 739, in login', '    (code, resp) = self.auth(', '                   ^^^^^^^^^^', '  File "/usr/lib/python3.11/smtplib.py", line 662, in auth', '    raise SMTPAuthenticationError(code, resp)', "smtplib.SMTPAuthenticationError: (535, b'Authentication failed')"]}
2023-10-12 13:15:53,645 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:15:53] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 13:17:26,195 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:17:29,697 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:17:31,330 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:17:31,331 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:17:33,071 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:17:33.070910
2023-10-12 13:17:34,130 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:17:34] "GET / HTTP/1.1" 200 -
2023-10-12 13:17:40,934 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:17:40] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:20:16,065 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:20:16] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:21:39,543 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:21:42,549 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:21:44,147 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:21:44,147 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:21:46,803 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:21:46.803141
2023-10-12 13:21:47,567 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:21:47] "GET / HTTP/1.1" 200 -
2023-10-12 13:21:52,489 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:21:52] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:22:29,201 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:22:31,857 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:22:33,466 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:22:33,467 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:22:36,747 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:22:36.746925
2023-10-12 13:22:37,513 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:22:37] "GET / HTTP/1.1" 200 -
2023-10-12 13:22:43,053 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:22:43] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:23:38,417 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:27:23,215 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:27:24,855 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:27:24,856 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:27:27,215 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:27:27.215404
2023-10-12 13:27:29,442 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:27:29] "GET / HTTP/1.1" 200 -
2023-10-12 13:27:34,268 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:27:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:29:28,352 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:29:31,630 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:29:33,285 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:29:33,285 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:29:34,854 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:29:34.853981
2023-10-12 13:29:35,547 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:29:35] "GET / HTTP/1.1" 200 -
2023-10-12 13:29:43,968 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:29:43] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:32:44,725 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:34:14,153 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:34:15,745 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:34:15,746 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:34:19,194 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:34:19.193879
2023-10-12 13:34:19,932 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:34:19] "GET / HTTP/1.1" 200 -
2023-10-12 13:34:24,724 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:34:24] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:35:31,216 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:35:34,034 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:35:35,690 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:35:35,691 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:38:48,345 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:44:44,455 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:44:46,139 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:44:46,140 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:44:49,775 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:44:49.775607
2023-10-12 13:44:49,797 INFO app Thread-7 (process_request_thread) : {'message': "Could not build url for endpoint 'link' with values ['link']. Did you mean 'static' instead?", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 104, in fetch_and_store_data', '    send_mail()', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 192, in send_mail', '    login_url = url_for(\'link\', link="https://docs.api.postnl.nl/#tag/Shipment/paths/~1shipment~1v2_2~1label/post" , _external=True)', '                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 225, in url_for', '    return current_app.url_for(', '           ^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1697, in url_for', '    return self.handle_url_build_error(error, endpoint, values)', '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1686, in url_for', '    rv = url_adapter.build(  # type: ignore[union-attr]', '         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 950, in build', '    raise BuildError(endpoint, values, method, self)', "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'link' with values ['link']. Did you mean 'static' instead?"]}
2023-10-12 13:44:49,800 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:44:49] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 13:45:07,105 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:45:08,704 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:45:10,305 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:45:10,306 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:45:11,529 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:45:11.529285
2023-10-12 13:45:11,559 INFO app Thread-7 (process_request_thread) : {'message': "Could not build url for endpoint 'link' with values ['link']. Did you mean 'static' instead?", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 104, in fetch_and_store_data', '    send_mail()', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 192, in send_mail', '    login_url = url_for(\'link\', link="https://docs.api.postnl.nl/#tag/Shipment/paths/~1shipment~1v2_2~1label/post" , _external=True)', '                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 225, in url_for', '    return current_app.url_for(', '           ^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1697, in url_for', '    return self.handle_url_build_error(error, endpoint, values)', '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1686, in url_for', '    rv = url_adapter.build(  # type: ignore[union-attr]', '         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 950, in build', '    raise BuildError(endpoint, values, method, self)', "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'link' with values ['link']. Did you mean 'static' instead?"]}
2023-10-12 13:45:11,563 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:45:11] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 13:45:12,290 INFO app Thread-8 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:45:12.290092
2023-10-12 13:45:12,306 INFO app Thread-8 (process_request_thread) : {'message': "Could not build url for endpoint 'link' with values ['link']. Did you mean 'static' instead?", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 104, in fetch_and_store_data', '    send_mail()', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 192, in send_mail', '    login_url = url_for(\'link\', link="https://docs.api.postnl.nl/#tag/Shipment/paths/~1shipment~1v2_2~1label/post" , _external=True)', '                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 225, in url_for', '    return current_app.url_for(', '           ^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1697, in url_for', '    return self.handle_url_build_error(error, endpoint, values)', '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1686, in url_for', '    rv = url_adapter.build(  # type: ignore[union-attr]', '         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 950, in build', '    raise BuildError(endpoint, values, method, self)', "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'link' with values ['link']. Did you mean 'static' instead?"]}
2023-10-12 13:45:12,308 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:45:12] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 13:45:12,531 INFO app Thread-9 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:45:12.530939
2023-10-12 13:45:12,562 INFO app Thread-9 (process_request_thread) : {'message': "Could not build url for endpoint 'link' with values ['link']. Did you mean 'static' instead?", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 104, in fetch_and_store_data', '    send_mail()', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 192, in send_mail', '    login_url = url_for(\'link\', link="https://docs.api.postnl.nl/#tag/Shipment/paths/~1shipment~1v2_2~1label/post" , _external=True)', '                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 225, in url_for', '    return current_app.url_for(', '           ^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1697, in url_for', '    return self.handle_url_build_error(error, endpoint, values)', '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1686, in url_for', '    rv = url_adapter.build(  # type: ignore[union-attr]', '         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 950, in build', '    raise BuildError(endpoint, values, method, self)', "werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'link' with values ['link']. Did you mean 'static' instead?"]}
2023-10-12 13:45:12,569 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:45:12] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 13:48:32,216 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:48:34,304 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:48:35,923 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:48:35,924 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:48:38,656 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:48:38.656673
2023-10-12 13:48:39,472 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:48:39] "GET / HTTP/1.1" 200 -
2023-10-12 13:48:44,553 INFO app Thread-8 (process_request_thread) : {'message': "test() missing 1 required positional argument: 'link'", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', "TypeError: test() missing 1 required positional argument: 'link'"]}
2023-10-12 13:48:44,555 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:48:44] "[35m[1mGET /link?link=https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 13:48:58,041 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:49:01,356 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:49:03,035 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:49:03,036 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:49:03,930 INFO app Thread-7 (process_request_thread) : {'message': "name 'link' is not defined", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 200, in test', '    return redirect(link)', '                    ^^^^', "NameError: name 'link' is not defined"]}
2023-10-12 13:49:03,932 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:49:03] "[35m[1mGET /link?link=https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 13:52:43,882 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:52:47,545 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:52:49,137 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:52:49,138 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:52:53,658 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:52:53.657877
2023-10-12 13:52:54,351 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:52:54] "GET / HTTP/1.1" 200 -
2023-10-12 13:52:59,281 INFO app Thread-8 (process_request_thread) : {'message': "name 'request' is not defined", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 198, in test', "    link = request.args.get('link')", '           ^^^^^^^', "NameError: name 'request' is not defined"]}
2023-10-12 13:52:59,282 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:52:59] "[35m[1mGET /test?link=https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 13:57:30,190 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 13:57:32,381 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 13:57:34,031 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 13:57:34,032 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 13:57:34,472 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test?link=https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,476 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,480 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,484 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,487 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,491 INFO werkzeug Thread-12 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,494 INFO werkzeug Thread-13 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,498 INFO werkzeug Thread-14 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,502 INFO werkzeug Thread-15 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,505 INFO werkzeug Thread-16 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,509 INFO werkzeug Thread-17 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,513 INFO werkzeug Thread-18 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,518 INFO werkzeug Thread-19 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,522 INFO werkzeug Thread-20 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,526 INFO werkzeug Thread-21 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,532 INFO werkzeug Thread-22 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,536 INFO werkzeug Thread-23 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,540 INFO werkzeug Thread-24 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,544 INFO werkzeug Thread-25 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:34,550 INFO werkzeug Thread-26 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:34] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,586 INFO werkzeug Thread-27 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,590 INFO werkzeug Thread-28 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,593 INFO werkzeug Thread-29 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,597 INFO werkzeug Thread-30 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,602 INFO werkzeug Thread-31 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,605 INFO werkzeug Thread-32 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,609 INFO werkzeug Thread-33 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,613 INFO werkzeug Thread-34 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,618 INFO werkzeug Thread-35 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,621 INFO werkzeug Thread-36 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,625 INFO werkzeug Thread-37 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,629 INFO werkzeug Thread-38 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,634 INFO werkzeug Thread-39 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,638 INFO werkzeug Thread-40 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,641 INFO werkzeug Thread-41 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,646 INFO werkzeug Thread-42 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,651 INFO werkzeug Thread-43 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,655 INFO werkzeug Thread-44 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,660 INFO werkzeug Thread-45 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:35,665 INFO werkzeug Thread-46 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:35] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,184 INFO werkzeug Thread-47 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,188 INFO werkzeug Thread-48 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,192 INFO werkzeug Thread-49 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,195 INFO werkzeug Thread-50 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,200 INFO werkzeug Thread-51 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,204 INFO werkzeug Thread-52 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,208 INFO werkzeug Thread-53 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,211 INFO werkzeug Thread-54 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,216 INFO werkzeug Thread-55 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,220 INFO werkzeug Thread-56 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,225 INFO werkzeug Thread-57 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,229 INFO werkzeug Thread-58 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,233 INFO werkzeug Thread-59 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,237 INFO werkzeug Thread-60 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,241 INFO werkzeug Thread-61 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,246 INFO werkzeug Thread-62 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,250 INFO werkzeug Thread-63 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,255 INFO werkzeug Thread-64 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,259 INFO werkzeug Thread-65 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:37,263 INFO werkzeug Thread-66 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:37] "[32mGET /test HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,325 INFO werkzeug Thread-67 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link?link=https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,336 INFO werkzeug Thread-68 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,340 INFO werkzeug Thread-69 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,346 INFO werkzeug Thread-70 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,351 INFO werkzeug Thread-71 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,355 INFO werkzeug Thread-72 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,359 INFO werkzeug Thread-73 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,364 INFO werkzeug Thread-74 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,369 INFO werkzeug Thread-75 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,373 INFO werkzeug Thread-76 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,378 INFO werkzeug Thread-77 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,384 INFO werkzeug Thread-78 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,389 INFO werkzeug Thread-79 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,394 INFO werkzeug Thread-80 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,401 INFO werkzeug Thread-81 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,406 INFO werkzeug Thread-82 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,410 INFO werkzeug Thread-83 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,416 INFO werkzeug Thread-84 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,421 INFO werkzeug Thread-85 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:39,425 INFO werkzeug Thread-86 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:39] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,466 INFO werkzeug Thread-87 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,471 INFO werkzeug Thread-88 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,475 INFO werkzeug Thread-89 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,480 INFO werkzeug Thread-90 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,485 INFO werkzeug Thread-91 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,489 INFO werkzeug Thread-92 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,493 INFO werkzeug Thread-93 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,499 INFO werkzeug Thread-94 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,503 INFO werkzeug Thread-95 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,507 INFO werkzeug Thread-96 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,511 INFO werkzeug Thread-97 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,516 INFO werkzeug Thread-98 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,520 INFO werkzeug Thread-99 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,525 INFO werkzeug Thread-100 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,530 INFO werkzeug Thread-101 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,535 INFO werkzeug Thread-102 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,540 INFO werkzeug Thread-103 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,545 INFO werkzeug Thread-104 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,550 INFO werkzeug Thread-105 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:40,555 INFO werkzeug Thread-106 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:40] "[32mGET /link HTTP/1.1[0m" 302 -
2023-10-12 13:57:44,745 INFO app Thread-107 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 13:57:44.745510
2023-10-12 13:57:45,453 INFO werkzeug Thread-107 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:45] "GET / HTTP/1.1" 200 -
2023-10-12 13:57:52,069 INFO app Thread-108 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 13:57:52,070 INFO werkzeug Thread-108 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:57:52] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 13:58:37,662 INFO app Thread-109 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 13:58:37,664 INFO werkzeug Thread-109 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:58:37] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 13:58:40,170 INFO app Thread-110 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 13:58:40,173 INFO werkzeug Thread-110 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:58:40] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 13:58:47,220 INFO app Thread-111 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 13:58:47,222 INFO werkzeug Thread-111 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:58:47] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 13:58:47,831 INFO app Thread-112 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 13:58:47,832 INFO werkzeug Thread-112 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:58:47] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 13:58:48,941 INFO app Thread-113 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 13:58:48,943 INFO werkzeug Thread-113 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:58:48] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 13:59:44,734 INFO app Thread-114 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 13:59:44,735 INFO werkzeug Thread-114 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 13:59:44] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 14:00:28,466 INFO app Thread-115 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 14:00:28,467 INFO werkzeug Thread-115 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:00:28] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 14:00:46,132 INFO app Thread-116 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 14:00:46,134 INFO werkzeug Thread-116 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:00:46] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 14:00:46,465 INFO app Thread-117 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 14:00:46,466 INFO werkzeug Thread-117 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:00:46] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 14:00:46,698 INFO app Thread-118 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 14:00:46,699 INFO werkzeug Thread-118 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:00:46] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 14:00:46,898 INFO app Thread-119 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 14:00:46,899 INFO werkzeug Thread-119 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:00:46] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 14:00:54,914 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 14:00:56,418 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 14:00:58,121 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 14:00:58,122 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 14:00:58,952 INFO app Thread-7 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 14:00:58,953 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:00:58] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 14:00:59,544 INFO app Thread-8 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 14:00:59,544 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:00:59] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 14:00:59,908 INFO app Thread-9 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 14:00:59,909 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:00:59] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 14:01:02,401 INFO app Thread-10 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 14:01:02.401574
2023-10-12 14:01:05,735 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:01:05] "GET / HTTP/1.1" 200 -
2023-10-12 14:01:10,926 INFO app Thread-11 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 14:01:10,927 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:01:10] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 14:04:34,687 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 14:04:38,896 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 14:04:40,553 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 14:04:40,554 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 14:04:41,228 INFO app Thread-7 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 14:04:41,230 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:04:41] "[35m[1mGET /https://docs.api.postnl.nl/%23tag/Shipment/paths/~1shipment~1v2_2~1label/post HTTP/1.1[0m" 500 -
2023-10-12 14:04:49,101 INFO app Thread-8 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 14:04:49.101479
2023-10-12 14:04:49,114 INFO app Thread-8 (process_request_thread) : {'message': "name 'login_url' is not defined", 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 104, in fetch_and_store_data', '    send_mail()', '  File "/home/tomz/Almec/Flask_start/template1/app.py", line 193, in send_mail', '    msg.html = f"Click the following link to see your track and trace: <a href=\'{login_url}\'>Click here</a>"', '                                                                                 ^^^^^^^^^', "NameError: name 'login_url' is not defined"]}
2023-10-12 14:04:49,116 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:04:49] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 14:05:03,633 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 14:05:05,528 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 14:05:07,201 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 14:05:07,202 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 14:05:07,466 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 14:05:07.466321
2023-10-12 14:05:09,712 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:05:09] "GET / HTTP/1.1" 200 -
2023-10-12 14:09:56,780 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 14:13:53,939 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 14:13:55,710 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 14:13:55,711 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 14:13:55,757 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 14:13:55.757180
2023-10-12 14:13:56,495 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:13:56] "GET / HTTP/1.1" 200 -
2023-10-12 14:16:09,042 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 14:38:54,278 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 14:39:32,688 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-12 14:39:32,689 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-12 14:39:32,693 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 14:39:34,308 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 14:39:34,309 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 14:39:37,593 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:39:37] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 14:39:37,676 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:39:37] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2023-10-12 14:39:37,679 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:39:37] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2023-10-12 14:39:37,702 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:39:37] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-12 14:39:37,721 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:39:37] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-12 14:39:59,447 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/forms.py', reloading
2023-10-12 14:40:01,458 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 14:40:55,965 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-12 14:40:55,965 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-12 14:40:55,966 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 14:41:12,630 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-12 14:41:12,630 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-12 14:41:12,631 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 14:41:14,319 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 14:41:14,319 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 14:41:14,375 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:41:14] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 14:41:14,400 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:41:14] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2023-10-12 14:41:14,403 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:41:14] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2023-10-12 14:41:14,418 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:41:14] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-12 14:41:14,440 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:41:14] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-12 14:42:37,492 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 14:42:37,996 INFO werkzeug Thread-12 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:42:37] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 14:42:38,075 INFO werkzeug Thread-13 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:42:38] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2023-10-12 14:42:39,335 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 14:42:41,165 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 14:42:41,166 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 14:42:41,216 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:42:41] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2023-10-12 14:42:41,227 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:42:41] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-12 14:42:41,239 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:42:41] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-12 14:42:45,863 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:42:45] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 14:42:45,878 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:42:45] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2023-10-12 14:42:45,884 INFO werkzeug Thread-12 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:42:45] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2023-10-12 14:42:45,901 INFO werkzeug Thread-13 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:42:45] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-12 14:42:45,920 INFO werkzeug Thread-14 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:42:45] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-12 14:44:34,476 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 14:44:37,887 INFO werkzeug Thread-15 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:44:37] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 14:44:37,921 INFO werkzeug Thread-16 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:44:37] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2023-10-12 14:44:38,925 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 14:44:40,676 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 14:44:40,677 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 14:44:40,726 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:44:40] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2023-10-12 14:44:40,738 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:44:40] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-12 14:44:40,753 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:44:40] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-12 14:44:41,517 INFO app Thread-10 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 14:44:41,518 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 14:44:41] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-12 15:08:25,701 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 15:08:28,437 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 15:08:30,106 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 15:08:30,107 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 15:08:30,432 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 15:08:30] "GET / HTTP/1.1" 200 -
2023-10-12 15:08:30,457 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 15:08:30] "[36mGET /static/form.css HTTP/1.1[0m" 304 -
2023-10-12 15:08:30,464 INFO app Thread-8 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request', '    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 502, in <lambda>', '    view_func=lambda **kw: self_ref().send_static_file(**kw),  # type: ignore # noqa: B950', '                           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/scaffold.py", line 317, in send_static_file', '    return send_from_directory(', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/helpers.py", line 557, in send_from_directory', '    return werkzeug.utils.send_from_directory(  # type: ignore[return-value]', '           ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/utils.py", line 574, in send_from_directory', '    raise NotFound()', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-12 15:08:30,464 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 15:08:30] "[35m[1mGET /static/style.css HTTP/1.1[0m" 500 -
2023-10-12 15:12:22,743 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-12 15:12:32,056 INFO werkzeug MainThread :  * Restarting with stat
2023-10-12 15:12:33,794 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-12 15:12:33,795 INFO werkzeug MainThread :  * Debugger PIN: 193-031-721
2023-10-12 15:12:33,847 INFO app Thread-7 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 15:12:33.847292
2023-10-12 15:12:34,650 INFO app Thread-7 (process_request_thread) : Email send successfully at 2023-10-12 15:12:34.649815
2023-10-12 15:12:34,691 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 15:12:34] "GET / HTTP/1.1" 200 -
2023-10-12 15:12:36,741 INFO app Thread-8 (process_request_thread) : Data fetched and stored successfully at 2023-10-12 15:12:36.741297
2023-10-12 15:12:37,424 INFO app Thread-8 (process_request_thread) : Email send successfully at 2023-10-12 15:12:37.424245
2023-10-12 15:12:37,433 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [12/Oct/2023 15:12:37] "GET / HTTP/1.1" 200 -
2023-10-12 15:20:02,179 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/models.py', reloading
2023-10-12 16:56:31,632 INFO werkzeug MainThread :  * Restarting with stat
2023-10-13 12:14:53,375 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-13 12:14:53,375 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-20 11:42:19,331 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-20 11:42:19,332 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-20 11:42:43,534 DEBUG urllib3.connectionpool Thread-6 (process_request_thread) : Starting new HTTP connection (1): localhost:5000
2023-10-20 11:42:43,538 ERROR app Thread-8 (process_request_thread) : Exception on /shipping/dropshipment [POST]
Traceback (most recent call last):
  File "/home/tomz/Almec/Flask_start/template1/app.py", line 157, in index
    api_data = request.get_json()
               ^^^^^^^
NameError: name 'request' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/Almec/Flask_start/template1/app.py", line 181, in index
    return internal_server_error(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/Almec/Flask_start/template1/app.py", line 58, in internal_server_error
    traceback_info = traceback.format_exc().strip().split("\n")
                     ^^^^^^^^^
NameError: name 'traceback' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1348, in handle_user_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/Almec/Flask_start/template1/app.py", line 58, in internal_server_error
    traceback_info = traceback.format_exc().strip().split("\n")
                     ^^^^^^^^^
NameError: name 'traceback' is not defined
2023-10-20 11:42:43,543 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:42:43] "[35m[1mPOST /shipping/dropshipment HTTP/1.1[0m" 500 -
2023-10-20 11:42:43,544 DEBUG urllib3.connectionpool Thread-6 (process_request_thread) : http://localhost:5000 "POST //shipping/dropshipment HTTP/1.1" 500 265
2023-10-20 11:42:43,546 ERROR app Thread-6 (process_request_thread) : Exception on / [GET]
Traceback (most recent call last):
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'test' did not return a valid response. The function either returned None or ended without a return statement.
2023-10-20 11:42:43,547 INFO werkzeug Thread-6 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:42:43] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-20 11:42:43,554 ERROR werkzeug Thread-6 (process_request_thread) : Error on request:
Traceback (most recent call last):
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1487, in full_dispatch_request
    return self.finalize_request(rv)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1506, in finalize_request
    response = self.make_response(rv)
               ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1801, in make_response
    raise TypeError(
TypeError: The view function for 'test' did not return a valid response. The function either returned None or ended without a return statement.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/serving.py", line 325, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1399, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/Almec/Flask_start/template1/app.py", line 58, in internal_server_error
    traceback_info = traceback.format_exc().strip().split("\n")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'traceback' is not defined
2023-10-20 11:42:43,555 ERROR werkzeug Thread-8 (process_request_thread) : Error on request:
Traceback (most recent call last):
  File "/home/tomz/Almec/Flask_start/template1/app.py", line 157, in index
    api_data = request.get_json()
               ^^^^^^^^^^^^^^^^^^
NameError: name 'request' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/Almec/Flask_start/template1/app.py", line 181, in index
    return internal_server_error(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/Almec/Flask_start/template1/app.py", line 58, in internal_server_error
    traceback_info = traceback.format_exc().strip().split("\n")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'traceback' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1348, in handle_user_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/Almec/Flask_start/template1/app.py", line 58, in internal_server_error
    traceback_info = traceback.format_exc().strip().split("\n")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'traceback' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/serving.py", line 325, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1399, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/Almec/Flask_start/template1/app.py", line 58, in internal_server_error
    traceback_info = traceback.format_exc().strip().split("\n")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'traceback' is not defined
2023-10-20 11:42:43,644 ERROR app Thread-7 (process_request_thread) : Exception on /favicon.ico [GET]
Traceback (most recent call last):
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1341, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1281, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/Almec/Flask_start/template1/app.py", line 58, in internal_server_error
    traceback_info = traceback.format_exc().strip().split("\n")
                     ^^^^^^^^^
NameError: name 'traceback' is not defined
2023-10-20 11:42:43,647 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:42:43] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
2023-10-20 11:42:43,650 ERROR werkzeug Thread-7 (process_request_thread) : Error on request:
Traceback (most recent call last):
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request
    self.raise_routing_exception(req)
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception
    raise request.routing_exception  # type: ignore
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request
    result = self.url_adapter.match(return_rule=True)  # type: ignore
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match
    raise NotFound() from None
werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1341, in handle_user_exception
    return self.handle_http_exception(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1281, in handle_http_exception
    return self.ensure_sync(handler)(e)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/Almec/Flask_start/template1/app.py", line 58, in internal_server_error
    traceback_info = traceback.format_exc().strip().split("\n")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'traceback' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/serving.py", line 364, in run_wsgi
    execute(self.server.app)
  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/serving.py", line 325, in execute
    application_iter = app(environ, start_response)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 2213, in __call__
    return self.wsgi_app(environ, start_response)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 2193, in wsgi_app
    response = self.handle_exception(e)
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1399, in handle_exception
    server_error = self.ensure_sync(handler)(server_error)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tomz/Almec/Flask_start/template1/app.py", line 58, in internal_server_error
    traceback_info = traceback.format_exc().strip().split("\n")
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
NameError: name 'traceback' is not defined
2023-10-20 11:43:33,940 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-20 11:43:33,941 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-20 11:43:33,961 INFO werkzeug MainThread :  * Restarting with stat
2023-10-20 11:43:55,370 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-20 11:43:55,370 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-20 11:43:55,372 INFO werkzeug MainThread :  * Restarting with stat
2023-10-20 11:43:57,017 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-20 11:43:57,018 INFO werkzeug MainThread :  * Debugger PIN: 698-641-762
2023-10-20 11:44:11,244 DEBUG urllib3.connectionpool Thread-7 (process_request_thread) : Starting new HTTP connection (1): localhost:5000
2023-10-20 11:44:11,261 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:44:11] "[35m[1mPOST /shipping/dropshipment HTTP/1.1[0m" 500 -
2023-10-20 11:44:11,262 DEBUG urllib3.connectionpool Thread-7 (process_request_thread) : http://localhost:5000 "POST //shipping/dropshipment HTTP/1.1" 500 22043
2023-10-20 11:44:25,213 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:44:25] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-20 11:44:25,250 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:44:25] "GET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1" 200 -
2023-10-20 11:44:25,250 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:44:25] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2023-10-20 11:44:25,276 INFO werkzeug Thread-12 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:44:25] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-20 11:44:25,291 INFO werkzeug Thread-13 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:44:25] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-20 11:44:54,065 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-20 11:44:56,192 INFO werkzeug MainThread :  * Restarting with stat
2023-10-20 11:44:57,946 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-20 11:44:57,947 INFO werkzeug MainThread :  * Debugger PIN: 698-641-762
2023-10-20 11:45:04,656 DEBUG urllib3.connectionpool Thread-7 (process_request_thread) : Starting new HTTP connection (1): localhost:5000
2023-10-20 11:46:11,898 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-20 11:46:13,582 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:46:13] "[35m[1mPOST /shipping/dropshipment HTTP/1.1[0m" 500 -
2023-10-20 11:46:13,611 DEBUG urllib3.connectionpool Thread-7 (process_request_thread) : http://localhost:5000 "POST //shipping/dropshipment HTTP/1.1" 500 22048
2023-10-20 11:46:13,767 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:46:13] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-20 11:46:14,571 INFO werkzeug MainThread :  * Restarting with stat
2023-10-20 11:46:16,382 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-20 11:46:16,382 INFO werkzeug MainThread :  * Debugger PIN: 698-641-762
2023-10-20 11:46:16,441 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:46:16] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2023-10-20 11:46:16,442 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:46:16] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2023-10-20 11:46:16,455 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:46:16] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-20 11:46:16,474 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:46:16] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-20 11:46:21,587 DEBUG urllib3.connectionpool Thread-11 (process_request_thread) : Starting new HTTP connection (1): localhost:5000
2023-10-20 11:47:26,180 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-20 11:47:27,310 INFO werkzeug Thread-13 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:47:27] "[35m[1mPOST /shipping/dropshipment HTTP/1.1[0m" 500 -
2023-10-20 11:47:27,334 DEBUG urllib3.connectionpool Thread-11 (process_request_thread) : http://localhost:5000 "POST //shipping/dropshipment HTTP/1.1" 500 22103
2023-10-20 11:47:27,442 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:47:27] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-20 11:47:28,117 INFO werkzeug MainThread :  * Restarting with stat
2023-10-20 11:47:29,997 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-20 11:47:29,998 INFO werkzeug MainThread :  * Debugger PIN: 698-641-762
2023-10-20 11:47:30,056 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:47:30] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2023-10-20 11:47:30,057 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:47:30] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2023-10-20 11:47:30,067 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:47:30] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-20 11:47:30,076 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:47:30] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-20 11:47:35,778 DEBUG urllib3.connectionpool Thread-11 (process_request_thread) : Starting new HTTP connection (1): localhost:5000
2023-10-20 11:47:49,920 INFO werkzeug Thread-13 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:47:49] "POST /shipping/dropshipment HTTP/1.1" 200 -
2023-10-20 11:47:49,922 DEBUG urllib3.connectionpool Thread-11 (process_request_thread) : http://localhost:5000 "POST //shipping/dropshipment HTTP/1.1" 200 45
2023-10-20 11:47:49,933 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:47:49] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-20 11:47:49,946 INFO werkzeug Thread-12 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:47:49] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2023-10-20 11:47:49,951 INFO werkzeug Thread-14 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:47:49] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2023-10-20 11:47:49,968 INFO werkzeug Thread-15 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:47:49] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-20 11:47:49,977 INFO werkzeug Thread-16 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 11:47:49] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-20 12:04:59,135 INFO werkzeug MainThread :  * Detected change in '/home/tomz/Almec/Flask_start/template1/app.py', reloading
2023-10-20 14:30:45,723 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-20 14:30:45,724 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-20 14:30:45,725 INFO werkzeug MainThread :  * Restarting with stat
2023-10-20 14:30:47,401 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-20 14:30:47,402 INFO werkzeug MainThread :  * Debugger PIN: 981-315-900
2023-10-20 14:30:52,838 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:30:52] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-20 14:30:52,942 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:30:52] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2023-10-20 14:30:52,944 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:30:52] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2023-10-20 14:30:52,969 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:30:52] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-20 14:36:30,488 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:36:30] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-20 14:36:30,499 INFO werkzeug Thread-14 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:36:30] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2023-10-20 14:36:30,502 INFO werkzeug Thread-15 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:36:30] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2023-10-20 14:36:30,516 INFO werkzeug Thread-16 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:36:30] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-20 14:36:30,547 INFO werkzeug Thread-17 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:36:30] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-20 14:37:01,000 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-20 14:37:01,001 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-20 14:37:01,002 INFO werkzeug MainThread :  * Restarting with stat
2023-10-20 14:37:20,384 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-20 14:37:20,385 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-20 14:37:20,386 INFO werkzeug MainThread :  * Restarting with stat
2023-10-20 14:37:22,062 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-20 14:37:22,063 INFO werkzeug MainThread :  * Debugger PIN: 981-315-900
2023-10-20 14:38:48,201 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:38:48] "[35m[1mGET / HTTP/1.1[0m" 500 -
2023-10-20 14:38:48,224 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:38:48] "[36mGET /?__debugger__=yes&cmd=resource&f=style.css HTTP/1.1[0m" 304 -
2023-10-20 14:38:48,227 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:38:48] "[36mGET /?__debugger__=yes&cmd=resource&f=debugger.js HTTP/1.1[0m" 304 -
2023-10-20 14:38:48,248 INFO werkzeug Thread-10 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:38:48] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-20 14:38:48,271 INFO werkzeug Thread-11 (process_request_thread) : 127.0.0.1 - - [20/Oct/2023 14:38:48] "[36mGET /?__debugger__=yes&cmd=resource&f=console.png HTTP/1.1[0m" 304 -
2023-10-24 13:10:22,704 INFO werkzeug MainThread : [31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on http://127.0.0.1:5000
2023-10-24 13:10:22,704 INFO werkzeug MainThread : [33mPress CTRL+C to quit[0m
2023-10-24 13:10:22,706 INFO werkzeug MainThread :  * Restarting with stat
2023-10-24 13:10:24,697 WARNING werkzeug MainThread :  * Debugger is active!
2023-10-24 13:10:24,698 INFO werkzeug MainThread :  * Debugger PIN: 393-892-104
2023-10-24 13:10:33,845 INFO werkzeug Thread-7 (process_request_thread) : 127.0.0.1 - - [24/Oct/2023 13:10:33] "GET / HTTP/1.1" 200 -
2023-10-24 13:10:33,968 INFO werkzeug Thread-8 (process_request_thread) : 127.0.0.1 - - [24/Oct/2023 13:10:33] "GET /static/form.css HTTP/1.1" 200 -
2023-10-24 13:10:33,981 INFO app Thread-9 (process_request_thread) : {'message': '404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.', 'traceback': ['Traceback (most recent call last):', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1484, in full_dispatch_request', '    rv = self.dispatch_request()', '         ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1458, in dispatch_request', '    self.raise_routing_exception(req)', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/app.py", line 1440, in raise_routing_exception', '    raise request.routing_exception  # type: ignore', '    ', '  File "/home/tomz/.local/lib/python3.11/site-packages/flask/ctx.py", line 353, in match_request', '    result = self.url_adapter.match(return_rule=True)  # type: ignore', '             ', '  File "/home/tomz/.local/lib/python3.11/site-packages/werkzeug/routing/map.py", line 655, in match', '    raise NotFound() from None', 'werkzeug.exceptions.NotFound: 404 Not Found: The requested URL was not found on the server. If you entered the URL manually please check your spelling and try again.']}
2023-10-24 13:10:33,983 INFO werkzeug Thread-9 (process_request_thread) : 127.0.0.1 - - [24/Oct/2023 13:10:33] "[35m[1mGET /favicon.ico HTTP/1.1[0m" 500 -
